services:
  # Backend service
  - type: web
    name: hostelhub-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /api/health

  # Frontend service
  - type: web
    name: hostelhub-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Frontend && npm install && npm run build
    startCommand: cd Frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://hostelhub-backend.onrender.com/api
    healthCheckPath: / 